@HostAddress = https://localhost:7312

### 

GET {{HostAddress}}/api/employee
Accept: application/json

###

GET {{HostAddress}}/api/employee/1
Accept: application/json

###

POST {{HostAddress}}/api/employee
Content-Type: application/json

{
  "FirstName": "John",
  "LastName": "Doe"
}

###

POST {{HostAddress}}/api/employee
Content-Type: application/json

{
  "FirstName": "Jane",
  "LastName": "Doe"
}

###

PUT {{HostAddress}}/api/employee/3
Content-Type: application/json

{
  "Id": 3,
  "FirstName": "Alice Updated",
  "LastName": "Johnson Updated"
}

###

DELETE {{HostAddress}}/api/employee/3

### 